CREATE TYPE degree AS ENUM ('ASSISTANT', 'ASSOCIATE_PROFESSOR', 'PROFESSOR');


CREATE TABLE department
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    head VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_department PRIMARY KEY (id)
);

CREATE TABLE department_lector
(
    department_id BIGINT NOT NULL,
    lector_id     BIGINT NOT NULL,
    CONSTRAINT pk_department_lector PRIMARY KEY (department_id, lector_id)
);

CREATE TABLE lector
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(255)                            NOT NULL,
    degree DEGREE,
    salary DECIMAL                                 NOT NULL,
    CONSTRAINT pk_lector PRIMARY KEY (id)
);

ALTER TABLE department_lector
    ADD CONSTRAINT fk_deplec_on_department FOREIGN KEY (department_id) REFERENCES department (id);

ALTER TABLE department_lector
    ADD CONSTRAINT fk_deplec_on_lector FOREIGN KEY (lector_id) REFERENCES lector (id);